### ISSUE TITLE
Variance weight AwesomeCloud JS plugin

### ISSUE THREAD

**Issue by leonogas** [timdream/wordcloud#38]
I want to show allways all the tags. My problem is when I have too many variance between them.

For example: With this tags and weight

all 0.5
rock 0.16666666666666666
artick 0.16666666666666666
xonaaa 0.16666666666666666
The output is: 
http://i.stack.imgur.com/fTVpT.png

And, sometimes, appear one more tag (artick). My opinion about this incorrect output are in the values for "size" and "factor" but I don't know what number I need to put there. I already try too many values and the output is always wrong. 
http://i.stack.imgur.com/1A7rM.png

What are the correct values to this case?

Tks

**Comment by timdream** [comment]
Are you sure `$().awesomeCloud()` wraps the library here :)? If so you are hitting the FAQ; the library here skips the word that couldn't fit into the canvas.

I am thinking about factoring the library to do two passes -- one for measure overall size and the other for actual drawing, but I have not yet have the time to do it.

**Comment by leonogas** [comment]
tks about your coment.
