### ISSUE TITLE
Not working with Hiragana on the web app

### ISSUE THREAD

**Issue by shichao-an** [timdream/wordcloud#39]
I upload the following file to the web app, but the rendered result does show Hiragana texts.

[fav.txt](https://github.com/timdream/wordcloud/files/56482/fav.txt)

![screen shot 2015-12-08 at 11 49 53 pm](https://cloud.githubusercontent.com/assets/5781687/11679506/6d14610a-9e06-11e5-8b38-5365f17d931f.png)

**Comment by timdream** [comment]
Hi!

Currently [wordfreq](https://github.com/timdream/wordfreq) does not support Japanese, so it simply filter out kana. I've been trying to implement that but so far there aren't any big progress.

I don't think I would have time to do it unfortunately.

**Comment by timdream** [comment]
If you want to generate an image with a list, you should use http://timdream.org/wordcloud2.js/

Or, tap on the "Edit List" button there to manually update the list to generate.

**Comment by shichao-an** [comment]
Thanks for your tip. http://timdream.org/wordcloud2.js/ seems really a nice web app, is it possible to export svg file from it also?

**Comment by timdream** [comment]
> Thanks for your tip. http://timdream.org/wordcloud2.js/ seems really a nice web app, is it possible to export svg file from it also?

It's not possible to get the glyph shapes and convert them to SVG without something like opentype.js, and even with it we would not have access to system fonts.

If we are only talking about arranging `<text>` in a cloud then it's totally doable -- patch welcome.

**Comment by shichao-an** [comment]
OK, thanks!
