### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by gbibas** [timdream/wordcloud#41]
When I load the script onto my server, I get the W and the small cloud bouncing back and forth, but nothing else happens.  Have tried reinstalling twice now.  Any ideas what I am doing wrong, or is there some setting I need to ensure is made on the server?

**Comment by timdream** [comment]
Any console output?

If you just need a cloud, https://github.com/timdream/wordcloud2.js instead.

**Comment by gbibas** [comment]
Thanks.  I will try the .js.  Just need a wordcloud for a page.

Thanks again for the help

Greg

**Comment by gbibas** [comment]
I want to read JSON from a file and produce a wordcloud from it.  Currently
it looks like your page is generated by putting the word list in index.js
which is called from Index.html

Where would I connect a JSON data object using your wordcloud2.js script?

Thanks

**Comment by timdream** [comment]
Please read https://github.com/timdream/wordcloud2.js/blob/master/API.md
