### ISSUE TITLE
how to generate default word cloud view at starting instead of other option???

### ISSUE THREAD

**Issue by kaushikandani** [timdream/wordcloud#42]
Hi

I want to load default word cloud with some predefined data instead of popup screen

Please give related help.

Thanks,
Kaushik

**Comment by timdream** [comment]
Once you are on the generated cloud view, click on [Edit] button and try to tweak the list a bit. The URL will be changed with the list embedded inside of it. Use and tweak that URL; load that URL will instantly draw the cloud.

Please comment if this is not what you want.

**Comment by kaushikandani** [comment]
hello 
i got below error

**Comment by kaushikandani** [comment]
Please Help for this error

NS_ERROR_FAILURE: 
ctx.font = size.toString(10) + 'px sans-serif';

wordcloud2.js (line 132)
ReferenceError: _gaq is not defined
	

_gaq.push(['_trackEvent',

	
start.js (line 42, col 3)
ReferenceError: WordCloud is not defined
	

!WordCloud.isSupported ||


Thanks,
Kaushik

**Comment by timdream** [comment]
I am confused. Are you trying to draw your own cloud by running your own WordCloud instance? If so you should try https://timdream.org/wordcloud2.js/ .

Both pages allow extensive customization for you to create the cloud online without running the code on your own.

**Comment by kaushikandani** [comment]
Hi,
i am generate wordcloud using iframe
but its generate error only in firefox browser - "NS_ERROR_FAILURE: "
in chrome its work.
Thanks,
Kaushik

**Comment by timdream** [comment]
I don't have enough information to fugue this out for you. Please use the DevTools debugger to find out where the error was thrown, and/or submit a reduced test case for others to reproduce.

**Comment by kaushikandani** [comment]
@timdream 
thanks for your help
my problem was solved
